# Generated by Django 4.2.25 on 2026-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_old_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('login', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Пользователь Cinema',
                'verbose_name_plural': 'Пользователи Cinema',
                'db_table': '"cinema"."users"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('txn_uuid', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.TextField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': '"cinema"."payments"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Покупка контента',
                'verbose_name_plural': 'Покупки контента',
                'db_table': '"cinema"."purchases"',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'managed': False, 'verbose_name': 'План подписки', 'verbose_name_plural': 'Планы подписок'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'managed': False, 'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
        migrations.DeleteModel(
            name='ContentPurchase',
        ),
    ]
