# Generated by Django 4.2.25 on 2026-01-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_current_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='"cinema"."subscription_plans"',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='"cinema"."user_subscriptions"',
        ),
    ]
